### ISSUE TITLE
libunrar-js error??  Invalid asm.js: Invalid member of stdlib

### ISSUE THREAD

**Issue by freekoy** [workhorsy/uncompress.js#18]
how to use this on Android web browser??
or libunrar-js (how to build wasm version???)

**Comment by workhorsy** [comment]
Unfortunately the Android branded web browser that comes with some versions of Android, is missing a ton of standard HTML and JS features. uncompress.js should work on Android using Chrome or Firefox.

**Comment by freekoy** [comment]
Can you write a tutorial how to compile into libunrar.js?
There are errors.
```
Invalid asm.js: Invalid member of stdlib
no native wasm Memory in use
Assertion failed: no binaryen method succeeded.
```

**Comment by workhorsy** [comment]
Unfortunately I don't have the original Emscripten code to generate the binary from source code. I just used the binaries provided by https://github.com/wcchoi/libunrar-js . I was trying to make a modern version using WebAssembly. It does not yet work correctly. I've been too busy to work on it: https://github.com/workhorsy/unrar.js

**Comment by tnikolai2** [comment]
https://github.com/tnikolai2/libunrar-js
I managed to compile new wasm version. Instructions in Readme.md

**Comment by workhorsy** [comment]
I'm closing this bug for now, as the problem was caused by the wrong web browser.
