### ISSUE TITLE
Extract archive to local directory

### ISSUE THREAD

**Issue by btzr-io** [workhorsy/uncompress.js#4]
Is there a way to extract an archive to a local directory using node.js?

**Comment by workhorsy** [comment]
I'm not familiar enough with Node. If you look at the trivial example, you might be able to write the result of readData to a file:
https://github.com/workhorsy/uncompress.js/blob/master/examples/trivial/main.js#L16

Any help with making this work with Node/NPM would be great.

**Comment by btzr-io** [comment]
Hi, I just start learning  node, but maybe  I can help :smile:

**Comment by btzr-io** [comment]
BTW I'm working on a comic book reader  app for Electron, 
like the one you made:  https://github.com/workhorsy/comic_book_reader

**Comment by workhorsy** [comment]
Nice. I'm really impressed with some of the Electron apps, such as Brave and Atom. If I had more time, I would look into using Electron for some projects.
