### ISSUE TITLE
Beautiful CODE!!! How can I extract and CBR file which is stored on server

### ISSUE THREAD

**Issue by inglesuniversal** [workhorsy/uncompress.js#7]
Hi, is there a way to get the file loaded and extracted from a URL rather than from an INPUT field

Example:

var file = "https://mydomain.com/files/family_trip.cbr";

**Comment by workhorsy** [comment]
I'll see if I can come up with an example for reading a file after downloading it.

**Comment by inglesuniversal** [comment]
Just an additional comment, now that I'm wide awake... "I've seen tons of JS code on github, but yours has a lot of TALENT behind it", KUDOS Sir Workhorsy!!!

**Comment by workhorsy** [comment]
I added a small example of how to download a file and extract it: http://workhorsy.github.io/uncompress.js/examples/download/index.html

The source code can be seen here: https://github.com/workhorsy/uncompress.js/tree/master/examples/download

**Comment by inglesuniversal** [comment]
Hello again... I added the script as directed and got this error...

XMLHttpRequest cannot load http://mydomain.com:3000/download/family_trip.cbr. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mydomain.com' is therefore not allowed access.
main.js:74 Failed to download file with status:  0
(anonymous) @ main.js:74
xhr.onreadystatechange @ main.js:16
main.js:74 Failed to download file with status:  undefined

**Comment by workhorsy** [comment]
If you are going to make a http request to a different domain, you need to take CORS into account: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

**Comment by workhorsy** [comment]
This looks like an issue with someone not understanding how browser security works with http requests. I'm going to close this bug, as it is not a problem with uncompress.js. Feel free to re-open it if there is an issue.
